name: Build and Push Backend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Get the commit hash
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build backend image
    - name: Build backend image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/kana-backend:latest -f ./backend/Dockerfile ./backend

    # Tag backend image with commit SHA
    - name: Tag backend image
      run: docker tag ghcr.io/${{ github.repository_owner }}/kana-backend:latest ghcr.io/${{ github.repository_owner }}/kana-backend:${{ steps.vars.outputs.sha_short }}

    # Push backend image
    - name: Push backend image
      run: docker push ghcr.io/${{ github.repository_owner }}/kana-backend:${{ steps.vars.outputs.sha_short }}


    # Modify the helm values to use the new image tag
    - name: Modify helm values
      run: |
        sed -i "s/tag: '[^']*'/tag: '${{ steps.vars.outputs.sha_short }}'/g" ./backend/.helm/kanas-backend/values.yaml

    ## COMMIT CHANGE
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        commit_message: "CI(Update): values charts -> tag"