name: Build and Push Frontend Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push-frontend:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build frontend image
    - name: Build frontend image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/kana-frontend:latest -f ./frontend/Dockerfile ./frontend

    # Tag frontend image with commit SHA
    - name: Tag frontend image
      run: docker tag ghcr.io/${{ github.repository_owner }}/kana-frontend:latest ghcr.io/${{ github.repository_owner }}/kana-frontend:${{ github.sha }}

    # Push frontend image
    - name: Push frontend image
      run: docker push ghcr.io/${{ github.repository_owner }}/kana-frontend:${{ github.sha }}

    # Modify the helm values to use the new image tag
    - name: Modify helm values
      run: |
        sed -i "s/tag: '[^']*'/tag: '${{ github.sha }}'/g" ./frontend/.helm/kanas-frontend/values.yaml

