name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Get the commit hash
    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build frontend image
    - name: Build frontend image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/kana-frontend:latest -f ./frontend/Dockerfile ./frontend

    # Tag frontend image with commit SHA
    - name: Tag frontend image
      run: docker tag ghcr.io/${{ github.repository_owner }}/kana-frontend:latest ghcr.io/${{ github.repository_owner }}/kana-frontend:${{ steps.vars.outputs.sha_short }}

    # Build backend image
    - name: Build backend image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/kana-backend:latest -f ./backend/Dockerfile ./backend

    # Tag backend image with commit SHA
    - name: Tag backend image
      run: docker tag ghcr.io/${{ github.repository_owner }}/kana-backend:latest ghcr.io/${{ github.repository_owner }}/kana-backend:${{ steps.vars.outputs.sha_short }}

    # Push frontend image
    - name: Push frontend image
      run: docker push ghcr.io/${{ github.repository_owner }}/kana-frontend:${{ steps.vars.outputs.sha_short }}

    # Push backend image
    - name: Push backend image
      run: docker push ghcr.io/${{ github.repository_owner }}/kana-backend:${{ steps.vars.outputs.sha_short }}

    # Modify helm values for frontend
    - name: Modify frontend helm values
      run: |
        sed -i "s/tag: '[^']*'/tag: '${{ steps.vars.outputs.sha_short }}'/g" ./frontend/.helm/kanas-frontend/values.yaml

    # Modify helm values for backend
    - name: Modify backend helm values
      run: |
        sed -i "s/tag: '[^']*'/tag: '${{ steps.vars.outputs.sha_short }}'/g" ./backend/.helm/kanas-backend/values.yaml

    ## COMMIT CHANGE
    - name: Commit and push changes
      uses: devops-infra/action-commit-push@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use PAT here
        commit_message: "CI(Update): values charts -> tag"