name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    # Checkout repository code
    - name: Checkout code
      uses: actions/checkout@v3

    # Log in to GitHub Container Registry
    - name: Log in to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # Build backend image
    - name: Build backend image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/kana-backend:latest -f ./backend/Dockerfile ./backend

    # Push backend image
    - name: Push backend image
      run: docker push ghcr.io/${{ github.repository_owner }}/kana-backend:latest

    # Build frontend image
    - name: Build frontend image
      run: docker build -t ghcr.io/${{ github.repository_owner }}/kana-frontend:latest -f ./frontend/Dockerfile ./frontend

    # Push frontend image
    - name: Push frontend image
      run: docker push ghcr.io/${{ github.repository_owner }}/kana-frontend:latest
